### ISSUE TITLE
모두 할일 : sourcetree를 이용한 git과 github 사용법 학습

### ISSUE THREAD

**Issue by gimdongwoo** [kosslab-kr/Titanium-BrandNew#11]
http://hackersstudy.tistory.com/41
를 참고하여 리파지터리에 소스 변경점을 push 해 봅니다.

(방법)
자신의 github계정으로 리파지터리를 만들고 테스트로 commit과 push를 해 봅니다.

(이후)
연습 이후에는 
https://github.com/kosslab-kr/Titanium-BrandNew 리파지터리를 로컬에 받아봅니다.
Create/New에서 Clone Repository를 이용합니다.

*\* (이후) 파트까지 성공한 사람들은 댓글 달아주세요.

**Comment by dbtmddus** [comment]
(이후)파트까지 했습니다~

**Comment by wkddnjset** [comment]
Create/New를 찾지 못했습니다 ㅠㅠ 근데 보니깐 여기 업로드 파일에 드래그를 통해서 파일 업로드가 가능한거 같은데 굳이 sourcetree를 쓰는 이유가 따로 있나요??

**Comment by gimdongwoo** [comment]
@wkddnjset git과 버전관리에 대해서 좀더 공부해보세요.
git이 유용한 이유는 변경된 내용에 대해 히스토리를 가지고 있어서 원하는 지점으로 돌아갈 수 있습니다.
그리고 같은 파일을 여러명이 수정하더라도 모든 변경점이 유지가 되거든요.
https://kmongcom.wordpress.com/2014/03/21/git-%EC%A0%95%EB%A7%90-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80/
요걸 잠깐 읽어보세요. 더 쉬운걸 찾으면 다시 알려드릴게요.
