### ISSUE TITLE
모두 할일 : Titanium 개발환경 구축

### ISSUE THREAD

**Issue by gimdongwoo** [kosslab-kr/Titanium-BrandNew#12]
https://www.youtube.com/playlist?list=PLAQybJIBW2UuW3_CzBTmnJq_ULw4zp4bu

위 동영상 강의를 차례로 학습하여 Titanium 개발환경을 구축합니다.

하면서 어려운 점이나 문제를 코멘트로 공유합니다.

*\* 쇼핑몰 컨텐츠 파서를 만드는 파트만을 하는 분들은 안하셔도 됩니다.

**Comment by wkddnjset** [comment]
Studio 는 다운 받았는데 CLI가 안드로이드 스튜디오에서 가상머신? 같은건가요??

**Comment by gimdongwoo** [comment]
CLI는 command line interface의 약자로 명령 프롬프트에서 사용할 수 있는 명령어를 제공한 것입니다.
Studio에서 gui를 이용한 방법도 있지만, 개발자는 명령어를 사용할 때 더 편리하게 작업할 수 있기 때문이죠.
