### ISSUE TITLE
팀장의 할일 : 팀원 각자의 역할을 정리

### ISSUE THREAD

**Issue by gimdongwoo** [kosslab-kr/Titanium-BrandNew#16]
해카톤 기간 동안 각각의 팀원이 맡은 할일을 간단히 정리해주세요.

**Comment by soulmade00** [comment]
최석환 : 서버에 저장되어 있는 URL을 가지고 서버에 URL로 데이터를 요청한뒤, 해당 URL의 데이터를 가져옴

**Comment by gimdongwoo** [comment]
최석환, 김유진, 이필구 - UI, Push

유승연, 조소영, 오충엽 - Parse Sever

서장원 - 웹문서, 구경, 리엑션, 신부름
