### ISSUE TITLE
유승연 : 가공한 데이터 mongo DB에 저장

### ISSUE THREAD

**Issue by dbtmddus** [kosslab-kr/Titanium-BrandNew#7]

**Comment by gimdongwoo** [comment]
mongo db에 저장하는 것은 parse-server를 이용해서, parse 객체를 저장하면 자동으로 이루어집니다.
(parse-server가 mongodb를 포함한 형태로 구성됩니다.)
- parse-server 셋팅 이후 data browser url을 공유할 것입니다.
