### ISSUE TITLE
팀장의 할일 : 서버를 제공할 heroku에 가입

### ISSUE THREAD

**Issue by gimdongwoo** [kosslab-kr/Titanium-BrandNew#9]
https://www.heroku.com/ 에 가입하고 아이디/비밀번호를 공유하면,

멘토가 그곳에 백앤드용 Parse Server 서버와 Mongo DB를 배포하고, 앱의 서버 정보를 반영하여 push 할 예정입니다.

**Comment by wkddnjset** [comment]
wkddnjset@naver.com
(삭제)
입니다!
